server:
  port: 5052
db:
  name: itemdb
spring:
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
eureka:
  client:
    serviceUrl:
      defaultZone: http://3.237.60.91:8761/eureka/
      
ui:
  serverUrl: http://localhost:4200/
management:
  endpoints:
    web:
      exposure:
        include: '*'